---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: I want to install webserver
    apt:
     name: apache2
     state: present
  - name: I want to copy my static file
    copy:
      src: mystaticfile.yml
      dest: /home/maha/

  - name: copy my dyno file from master to node
    copy:
      src: mydynofile.j2
      dest: /var/www/html/index.html

  - name: download internet files into node side
    get_url:
      url: https://adp-mirror-vm1-he-fi.apache.org/tomcat/tomcat-10/v10.0.0/bin/apache-tomcat-10.0.0-windows-x64.zip
      dest: /etc/foo.conf
      force_basic_auth: yes



