---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu ansible node
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: In task, I want  to start apache2 webserver on ubuntu ansible nodes
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"
  
