---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu ansible node
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: In task, I want  to start apache2 webserver on ubuntu ansible nodes
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"
  
  - name: In task, I want  to install httpd server on red hat linux machine
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: In task, I want  to start httpd server on red hat linux machine
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"