---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache2 webserver on ubuntu ansible node
    apt:
      name: apache2
      state: present
  - name: In task, I want  to start apache2 webserver on ubuntu ansible nodes
    service:
      name: apache2
      state: started    
